[server]
    [server.rpc]
        addr = "0.0.0.0:0"
        timeout = "1s"
        idleTimeout = "180s"
        maxLifeTime = "2h"
        forceCloseWait = "20s"
        keepAliveInterval = "60s"
        keepAliveTimeout = "20s"
        slowRequestDuration = "500ms"
        watchConfig = true

[etcd]
    prefix = "waterdrop"
    endpoints = ["127.0.0.1:2379"]
    dialTimeout = "1s"
    registerTTL = "90s"
    username = ""
    password = ""

[client]
    [client.rpc]
        [client.rpc.demo]
            key = "xHf74ZfV43cAUsUl"
            secret = "d0dbe915091d400bd8ee7f27f0791303"
            dialTimeout = "10s"
            block = true
            balancer = "round_robin"
            target = "etcd://default/service.user.v1"
            timeout = "500ms"
            keepAliveInterval = "60s"
            keepAliveTimeout = "20s"
            slowRequestDuration = "500ms"

[stats]
    addr = "0.0.0.0:20828"
    mode = "debug"
    enableMetric = true
    enableProfile = true